## https://fsymbols.com/generators/tarty/

#███╗░░░███╗░█████╗░██╗███╗░░██╗
#████╗░████║██╔══██╗██║████╗░██║
#██╔████╔██║███████║██║██╔██╗██║
#██║╚██╔╝██║██╔══██║██║██║╚████║
#██║░╚═╝░██║██║░░██║██║██║░╚███║
#╚═╝░░░░░╚═╝╚═╝░░╚═╝╚═╝╚═╝░░╚══╝

name: AutoRestart
version: 4.1.0
build: 69
main: org.serversmc.autorestart.core.Main
softdepend:
    - PlaceholderAPI
authors:
    - ServersMC
    - DennisLysenko
website: https://www.spigotmc.org/resources/autorestart.2538/
email: info@serversmc.org
description: "Automatically restarts your server with customizable messages, and seamless integrations"

#░█████╗░███╗░░░███╗██████╗░░██████╗
#██╔══██╗████╗░████║██╔══██╗██╔════╝
#██║░░╚═╝██╔████╔██║██║░░██║╚█████╗░
#██║░░██╗██║╚██╔╝██║██║░░██║░╚═══██╗
#╚█████╔╝██║░╚═╝░██║██████╔╝██████╔╝
#░╚════╝░╚═╝░░░░░╚═╝╚═════╝░╚═════╝░

commands:
    autore:
        description: "AutoRestart Command"
        permission: "autorestart"
        permission-message: "Surprisingly they don't want you using this command?"
    
#██████╗░███████╗██████╗░███╗░░░███╗░██████╗
#██╔══██╗██╔════╝██╔══██╗████╗░████║██╔════╝
#██████╔╝█████╗░░██████╔╝██╔████╔██║╚█████╗░
#██╔═══╝░██╔══╝░░██╔══██╗██║╚██╔╝██║░╚═══██╗
#██║░░░░░███████╗██║░░██║██║░╚═╝░██║██████╔╝
#╚═╝░░░░░╚══════╝╚═╝░░╚═╝╚═╝░░░░░╚═╝╚═════╝░

permissions:
    #▒█▀▀▄ ▒█▀▀▀ ▒█▀▀▀ ░█▀▀█ ▒█░▒█ ▒█░░░ ▀▀█▀▀
    #▒█░▒█ ▒█▀▀▀ ▒█▀▀▀ ▒█▄▄█ ▒█░▒█ ▒█░░░ ░▒█░░
    #▒█▄▄▀ ▒█▄▄▄ ▒█░░░ ▒█░▒█ ░▀▄▄▀ ▒█▄▄█ ░▒█░░
    autorestart: {}
    autorestart.help: {}
    autorestart.time: {}
    
    #░█▀▀█ ▒█▀▀▄ ▒█▀▄▀█ ▀█▀ ▒█▄░▒█
    #▒█▄▄█ ▒█░▒█ ▒█▒█▒█ ▒█░ ▒█▒█▒█
    #▒█░▒█ ▒█▄▄▀ ▒█░░▒█ ▄█▄ ▒█░░▀█
    autorestart.admin:
        children:
            - autorestart.in
            - autorestart.now
            - autorestart.pause
            - autorestart.resume
    autorestart.in: {}
    autorestart.now: {}
    autorestart.pause: {}
    autorestart.resume: {}
    
    #░█▀▀█ ▒█░░░ ▒█░░░
    #▒█▄▄█ ▒█░░░ ▒█░░░
    #▒█░▒█ ▒█▄▄█ ▒█▄▄█
    autorestart.*:
        children:
            - autorestart.help
            - autorestart.time
            - autorestart.resume
            - autorestart.pause
            - autorestart.in
            - autorestart.reload
            - autorestart.now