name: AutoRestart
description: "Automatically restarts your server with customizable messages, and seamless integrations"

version: 4.1.0
build: 69
main: org.serversmc.autorestart.core.Main
softdepend:
    - PlaceholderAPI

authors:
    - ServersMC
    - DennisLysenko
website: http://spigotmc.org/
email: info@serversmc.org

commands:
    autore:
        description: "AutoRestart Command"
        usage: "/autore <help>"