## https://fsymbols.com/generators/tarty/

#███╗░░░███╗░█████╗░██╗███╗░░██╗
#████╗░████║██╔══██╗██║████╗░██║
#██╔████╔██║███████║██║██╔██╗██║
#██║╚██╔╝██║██╔══██║██║██║╚████║
#██║░╚═╝░██║██║░░██║██║██║░╚███║
#╚═╝░░░░░╚═╝╚═╝░░╚═╝╚═╝╚═╝░░╚══╝

name: AutoRestart
version: 4.1.1
build: 70
main: org.serversmc.autorestart.core.Main
softdepend:
    - PlaceholderAPI
authors:
    - ServersMC
    - DennisLysenko
website: https://www.spigotmc.org/resources/autorestart.2538/
email: info@serversmc.org
description: "Automatically restarts your server with customizable messages, and seamless integrations"

#░█████╗░███╗░░░███╗██████╗░░██████╗
#██╔══██╗████╗░████║██╔══██╗██╔════╝
#██║░░╚═╝██╔████╔██║██║░░██║╚█████╗░
#██║░░██╗██║╚██╔╝██║██║░░██║░╚═══██╗
#╚█████╔╝██║░╚═╝░██║██████╔╝██████╔╝
#░╚════╝░╚═╝░░░░░╚═╝╚═════╝░╚═════╝░

commands:
    autore:
        description: "AutoRestart Command"
        permission: "autorestart"
        permission-message: "Surprisingly they don't want you using this command?"
    
#██████╗░███████╗██████╗░███╗░░░███╗░██████╗
#██╔══██╗██╔════╝██╔══██╗████╗░████║██╔════╝
#██████╔╝█████╗░░██████╔╝██╔████╔██║╚█████╗░
#██╔═══╝░██╔══╝░░██╔══██╗██║╚██╔╝██║░╚═══██╗
#██║░░░░░███████╗██║░░██║██║░╚═╝░██║██████╔╝
#╚═╝░░░░░╚══════╝╚═╝░░╚═╝╚═╝░░░░░╚═╝╚═════╝░

permissions:
    #▒█▀▀▄ ▒█▀▀▀ ▒█▀▀▀ ░█▀▀█ ▒█░▒█ ▒█░░░ ▀▀█▀▀
    #▒█░▒█ ▒█▀▀▀ ▒█▀▀▀ ▒█▄▄█ ▒█░▒█ ▒█░░░ ░▒█░░
    #▒█▄▄▀ ▒█▄▄▄ ▒█░░░ ▒█░▒█ ░▀▄▄▀ ▒█▄▄█ ░▒█░░
    autorestart: 
        default: true
    autorestart.help:
        default: true
    autorestart.time:
        default: true
    
    #░█▀▀█ ▒█▀▀▄ ▒█▀▄▀█ ▀█▀ ▒█▄░▒█
    #▒█▄▄█ ▒█░▒█ ▒█▒█▒█ ▒█░ ▒█▒█▒█
    #▒█░▒█ ▒█▄▄▀ ▒█░░▒█ ▄█▄ ▒█░░▀█
    autorestart.admin:
        children:
            autorestart.in: true
            autorestart.now: true
            autorestart.pause: true
            autorestart.resume: true
    autorestart.in: {}
    autorestart.now: {}
    autorestart.pause: {}
    autorestart.resume: {}
    
    #░█▀▀█ ▒█░░░ ▒█░░░
    #▒█▄▄█ ▒█░░░ ▒█░░░
    #▒█░▒█ ▒█▄▄█ ▒█▄▄█
    autorestart.*:
        children:
            autorestart.help: true
            autorestart.time: true
            autorestart.resume: true
            autorestart.pause: true
            autorestart.in: true
            autorestart.reload: true
            autorestart.now: true