## https://fsymbols.com/generators/tarty/

#███╗░░░███╗░█████╗░██╗███╗░░██╗
#████╗░████║██╔══██╗██║████╗░██║
#██╔████╔██║███████║██║██╔██╗██║
#██║╚██╔╝██║██╔══██║██║██║╚████║
#██║░╚═╝░██║██║░░██║██║██║░╚███║
#╚═╝░░░░░╚═╝╚═╝░░╚═╝╚═╝╚═╝░░╚══╝

name: AutoRestart
version: ${project.version}
build: 76
main: org.serversmc.autorestart.core.Main
softdepend:
  - PlaceholderAPI
authors:
  - ServersMC
  - DennisLysenko
  - Edgeburn Media
website: https://www.spigotmc.org/resources/autorestart.2538/
email: support@mailredirect.edgeburnmedia.com
description: "Automatically restarts your server with customizable messages, and seamless integrations"

#░█████╗░███╗░░░███╗██████╗░░██████╗
#██╔══██╗████╗░████║██╔══██╗██╔════╝
#██║░░╚═╝██╔████╔██║██║░░██║╚█████╗░
#██║░░██╗██║╚██╔╝██║██║░░██║░╚═══██╗
#╚█████╔╝██║░╚═╝░██║██████╔╝██████╔╝
#░╚════╝░╚═╝░░░░░╚═╝╚═════╝░╚═════╝░

commands:
  autore:
    description: "AutoRestart Command"
    permission-message: "Surprisingly they don't want you using this command?"

#██████╗░███████╗██████╗░███╗░░░███╗░██████╗
#██╔══██╗██╔════╝██╔══██╗████╗░████║██╔════╝
#██████╔╝█████╗░░██████╔╝██╔████╔██║╚█████╗░
#██╔═══╝░██╔══╝░░██╔══██╗██║╚██╔╝██║░╚═══██╗
#██║░░░░░███████╗██║░░██║██║░╚═╝░██║██████╔╝
#╚═╝░░░░░╚══════╝╚═╝░░╚═╝╚═╝░░░░░╚═╝╚═════╝░

permissions:
  autorestart.admin:
    children:
      autorestart.in: true
      autorestart.now: true
      autorestart.pause: true
      autorestart.resume: true
  autorestart.*:
    children:
      autorestart.help: true
      autorestart.time: true
      autorestart.resume: true
      autorestart.pause: true
      autorestart.in: true
      autorestart.reload: true
      autorestart.now: true