## Global Broadcast and Private Messages adds flexibility on what you want your players to see!
## You have the option of having the player who executed the event to see a message while other don't, or
## have the player who executed the event see a global message but not a private message
## you can have the server see a global message while the player who executed the command will see
## his own message.

## The reason why you can enable or disable broadcasts and popups, is to give you the flexibility to
## choose whether you want your players to see a broadcast or a popup of the event. Or both! If you have
## both popups and broadcasts disabled, broadcasts are automatically enabled. If broadcasts, private messages,
## and popups are all disabled, then it will as well be automatically enabled in broadcasts. If broadcasts and
## private messages are disabled, but popups are enabled, console will get a private message for logs. Since
## command line cant receive popups.
    
## These are global broadcasts the everyone sees. If the same task is enabled in "private_message"
##  the player who initiated the event will not see the broadcast, but will see his own broadcast.
##  Global broadcasts include the prefix in "main.prefix" config.

## Messages have multi line support!
global_broadcast:
    ## Show the broadcast on the minute reminders!
    minutes:
        enabled: true
        ## %m - minutes
        message:
            - 'Server Will Restart In %m Minutes!'
    ## Show the broadcast on the last seconds of a server restart!
    seconds:
        enabled: true
        ## %s - seconds
        message:
            - 'Server is restarting in %s Seconds!'
    ## Show the broadcast when typed /autore resume or /autore pause
    status:
        ## Show the broadcast when typed /autore resume
        resume:
            enabled: true
            ## There are no tags for this section.
            message:
                - '&cAutoRestart timer has resumed!'
        ## Show the broadcast when typed /autore pause
        pause:
            enabled: true
            ## There are no tags for this section.
            message:
                - '&cAutoRestart timer has been paused'
    ## Show the broadcast when the server time has been changed!
    change:
        enabled: true
        message:
            - '&cServer now is restarting in &f%h&cH &f%m&cM &f%s&cS!'
    ## Show the Maxplayers broadcast
    max_players:
        ## The message broadcasted when too many players are online on restart!
        alert:
            enabled: true
            message:
                - '&bToo many players online for restart. Max &f%a&b amount of players allowed for a restart. Waiting for people to leave!'
        ## This message appears when the amount of players requirement is met!
        pre_shutdown:
            enabled: true
            message:
                - '&aServer now restarting in &f%d&a seconds!'
    ## Global shutdown message
    shutdown:
        enabled: true
        message:
            - '&cServer Restarting!'
## DO NOT TOUCH!!
version: 2