## Main configuration values
main:
    ## Recalculate timer on config reload
    ## This will recalculate the restart countdown when using '/autore reload'
    recalculate_onreload: false
    ## restart modes available 'interval', and 'timestamp'
    restart_mode: 'interval'
    ## restart mode specific settings
    modes:
        ## Restart server in intervals
        ## In hours or daily
        interval:
            ## Set the multiplication factor
            ## Options are 'hours' or 'days'
            factor: 'hours'
            ## Set the actual value of the interval
            ## If you set factor to 'hours' and value is 4
            ##   Server will restart in 4 hours
            ## If factor is set to days
            ##   Server will restart in 4 days
            ## Decimals are allowed
            value: 3.0
        ## Set the timestamp in 24 hour time format HH:MM
        ## Multiple timestamps allowed
        timestamp:
            - '0:00'
            - '6:00'
            - '12:00'
            - '18:00'
    ## Server wide prefix for all chat broadcasts
    prefix: '&f[&7AutoRestart&f] &e'
    ## Client restart message in game chat
    kick_message: '&cServer Restarting! We will be back up any minute!'
## DO NOT TOUCH!!
version: 5